version: "2"
plugins:
  radon:
    enabled: true
  pylint:
    enabled: true
    checks:
      invalid-name:
        enabled: false # Allows using short variables like n and i
      bad-continuation:
        enabled: false # Black can handle this
exclude_patterns:
- "submit.py"
